import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const products = [
  // ── Electronics ─────────────────────────────────────────────────────────
  {
    name: "Apple AirPods Pro (2nd Gen)",
    shortDescription: "Active noise cancellation with adaptive audio and H2 chip.",
    description: "Experience next-level audio with AirPods Pro featuring Adaptive Audio that continuously blends Active Noise Cancellation and Transparency mode. The H2 chip enables smarter noise cancellation, computational audio, and all-day battery life.",
    price: 24900,
    discountPercent: 10,
    salePrice: 22410,
    brand: "Apple",
    sku: "APPL-APP-2G",
    stock: 45,
    status: "published",
    highlights: ["Active Noise Cancellation", "Adaptive Transparency", "Up to 30hr battery with case", "MagSafe charging case", "IPX4 water resistant"],
    tags: ["airpods", "earbuds", "apple", "wireless", "noise-cancelling"],
    categorySlug: "headphones-earbuds",
    sizes: [],
    colors: [],
    images: { default: "https://images.unsplash.com/photo-1606841837239-c5a1a4a07af7?w=800&q=80" },
  },
  {
    name: "Samsung 65\" 4K QLED Smart TV",
    shortDescription: "Quantum Dot technology with vibrant colours and AI upscaling.",
    description: "Immerse yourself in stunning 4K visuals powered by Quantum Dot technology. The Neural Quantum Processor 4K intelligently upscales content, while Object Tracking Sound delivers audio precisely from where the action happens on screen.",
    price: 129900,
    discountPercent: 15,
    salePrice: 110415,
    brand: "Samsung",
    sku: "SAM-TV-65Q",
    stock: 12,
    status: "published",
    highlights: ["4K QLED Display", "Neural Quantum Processor", "Object Tracking Sound+", "SmartThings compatible", "100% Colour Volume"],
    tags: ["tv", "samsung", "4k", "smart-tv", "qled"],
    categorySlug: "tv-home-theatre",
    sizes: [],
    colors: [],
    images: { default: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&q=80" },
  },
  {
    name: "Sony WH-1000XM5 Headphones",
    shortDescription: "Industry-leading noise cancellation with 30-hour battery.",
    description: "The WH-1000XM5 headphones feature eight microphones and two processors for unprecedented noise cancellation. Auto NC Optimizer automatically optimises noise cancellation based on your wearing conditions and environment.",
    price: 39900,
    discountPercent: 20,
    salePrice: 31920,
    brand: "Sony",
    sku: "SONY-WH1000XM5",
    stock: 30,
    status: "published",
    highlights: ["Industry-leading noise cancellation", "30-hour battery life", "Speak-to-Chat technology", "Multipoint connection", "Foldable design"],
    tags: ["headphones", "sony", "noise-cancelling", "wireless", "over-ear"],
    categorySlug: "headphones-earbuds",
    sizes: [],
    colors: ["black", "silver"],
    images: {
      black: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800&q=80",
      silver: "https://images.unsplash.com/photo-1619741497048-c4b2cf6f62db?w=800&q=80",
    },
  },

  // ── Fashion ──────────────────────────────────────────────────────────────
  {
    name: "Classic Fit Oxford Shirt",
    shortDescription: "Premium cotton Oxford shirt for work or weekend wear.",
    description: "Crafted from 100% premium cotton Oxford cloth, this shirt offers a comfortable classic fit that works equally well in the office or on the weekend. The button-down collar stays neat all day while the slightly relaxed cut allows ease of movement.",
    price: 6900,
    discountPercent: 0,
    brand: "Veloria Basics",
    sku: "VB-SHIRT-OXF",
    stock: 120,
    status: "published",
    highlights: ["100% premium cotton", "Button-down collar", "Machine washable", "Classic relaxed fit", "Available in 3 colours"],
    tags: ["shirt", "oxford", "men", "casual", "formal"],
    categorySlug: "mens-clothing",
    sizes: ["s", "m", "l", "xl", "xxl"],
    colors: ["white", "blue", "gray"],
    images: {
      white: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&q=80",
      blue: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800&q=80",
      gray: "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&q=80",
    },
  },
  {
    name: "Women's Floral Midi Dress",
    shortDescription: "Elegant floral print dress perfect for any occasion.",
    description: "This beautiful midi dress features an all-over floral print on soft, breathable fabric. The wrap-style bodice flatters all body types while the flowing midi-length skirt moves elegantly. Perfect for brunches, garden parties, or casual evenings out.",
    price: 7900,
    discountPercent: 25,
    salePrice: 5925,
    brand: "Veloria Fashion",
    sku: "VF-DRESS-FL",
    stock: 65,
    status: "published",
    highlights: ["Soft breathable fabric", "Wrap-style bodice", "Midi length", "Floral print", "Adjustable tie waist"],
    tags: ["dress", "floral", "women", "midi", "summer"],
    categorySlug: "womens-clothing",
    sizes: ["xs", "s", "m", "l", "xl"],
    colors: ["pink", "blue"],
    images: {
      pink: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=800&q=80",
      blue: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&q=80",
    },
  },
  {
    name: "Men's Running Sneakers",
    shortDescription: "Lightweight, cushioned running shoes for everyday training.",
    description: "Engineered for performance and comfort, these running sneakers feature a breathable mesh upper and a responsive foam midsole that returns energy with every stride. The rubber outsole provides reliable grip on both roads and light trails.",
    price: 11900,
    discountPercent: 10,
    salePrice: 10710,
    brand: "SpeedRun",
    sku: "SR-SHOE-RUN",
    stock: 80,
    status: "published",
    highlights: ["Breathable mesh upper", "Responsive foam cushioning", "Energy-return midsole", "Rubber outsole grip", "Lightweight 285g"],
    tags: ["shoes", "running", "men", "sneakers", "sport"],
    categorySlug: "mens-shoes",
    sizes: ["40", "41", "42", "43", "44", "45"],
    colors: ["black", "white", "gray"],
    images: {
      black: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
      white: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&q=80",
      gray: "https://images.unsplash.com/photo-1539185441755-769473a23570?w=800&q=80",
    },
  },
  {
    name: "Leather Tote Handbag",
    shortDescription: "Spacious genuine leather tote for work and everyday use.",
    description: "Made from full-grain genuine leather, this tote bag ages beautifully and only gets better with use. The spacious main compartment fits a 15\" laptop, and the multiple interior pockets keep everything organised. Reinforced handles and a detachable shoulder strap offer versatile carrying options.",
    price: 18900,
    discountPercent: 0,
    brand: "LuxCarry",
    sku: "LC-BAG-TOTE",
    stock: 25,
    status: "published",
    highlights: ["Full-grain genuine leather", "Fits 15\" laptop", "Multiple interior pockets", "Detachable shoulder strap", "Antique brass hardware"],
    tags: ["handbag", "leather", "women", "tote", "work"],
    categorySlug: "handbags-wallets",
    sizes: [],
    colors: ["brown", "black"],
    images: {
      brown: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=80",
      black: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&q=80",
    },
  },

  // ── Beauty & Health ──────────────────────────────────────────────────────
  {
    name: "Vitamin C Brightening Serum",
    shortDescription: "Potent 20% Vitamin C serum for glowing, even-toned skin.",
    description: "This dermatologist-tested serum features 20% L-ascorbic acid combined with vitamin E and ferulic acid for maximum stability and effectiveness. It visibly reduces dark spots, brightens skin tone, and provides antioxidant protection against environmental damage.",
    price: 3900,
    discountPercent: 0,
    brand: "GlowLab",
    sku: "GL-SER-VC20",
    stock: 200,
    status: "published",
    highlights: ["20% Vitamin C (L-ascorbic acid)", "Vitamin E + Ferulic Acid", "Reduces dark spots in 4 weeks", "Dermatologist tested", "All skin types"],
    tags: ["serum", "vitamin-c", "skincare", "brightening", "anti-aging"],
    categorySlug: "skincare",
    sizes: [],
    colors: [],
    images: { default: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&q=80" },
  },
  {
    name: "Luxury Perfume — Oud & Rose",
    shortDescription: "Intense oriental fragrance with premium oud and Bulgarian rose.",
    description: "An opulent oriental fragrance that opens with bergamot and saffron, unfolds into a heart of Bulgarian rose and oud wood, and settles into a warm base of amber, musk, and sandalwood. Long-lasting 12+ hour projection.",
    price: 12900,
    discountPercent: 0,
    brand: "Maison Veloria",
    sku: "MV-PERF-OR",
    stock: 40,
    status: "published",
    highlights: ["Top: Bergamot, Saffron", "Heart: Bulgarian Rose, Oud", "Base: Amber, Musk, Sandalwood", "12+ hour longevity", "100ml Eau de Parfum"],
    tags: ["perfume", "fragrance", "oud", "rose", "luxury"],
    categorySlug: "fragrances",
    sizes: [],
    colors: [],
    images: { default: "https://images.unsplash.com/photo-1541643600914-78b084683702?w=800&q=80" },
  },

  // ── Home & Kitchen ───────────────────────────────────────────────────────
  {
    name: "Stainless Steel Cookware Set (5-Piece)",
    shortDescription: "Professional-grade cookware set for everyday cooking.",
    description: "This 5-piece stainless steel cookware set includes everything you need for daily cooking: 20cm saucepan, 24cm frying pan, 28cm frying pan, 24cm sauté pan, and a stockpot. Tri-ply construction ensures even heat distribution and eliminates hot spots.",
    price: 15900,
    discountPercent: 20,
    salePrice: 12720,
    brand: "ChefPro",
    sku: "CP-COOK-5PC",
    stock: 35,
    status: "published",
    highlights: ["Tri-ply stainless steel", "5-piece complete set", "Oven safe to 260°C", "Compatible with all cooktops incl. induction", "Dishwasher safe"],
    tags: ["cookware", "kitchen", "stainless-steel", "chef", "cooking"],
    categorySlug: "kitchen-dining",
    sizes: [],
    colors: [],
    images: { default: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=800&q=80" },
  },
  {
    name: "Memory Foam Pillow",
    shortDescription: "Ergonomic cervical pillow for side and back sleepers.",
    description: "Designed with a contoured cervical shape, this memory foam pillow supports natural spinal alignment for side and back sleepers. The breathable bamboo cover wicks moisture and regulates temperature, while the medium-firm density adapts to your unique shape for personalised comfort.",
    price: 5900,
    discountPercent: 0,
    brand: "SleepWell",
    sku: "SW-PILL-MF",
    stock: 90,
    status: "published",
    highlights: ["Contoured cervical shape", "CertiPUR-US certified foam", "Bamboo cooling cover", "Hypoallergenic", "Machine-washable cover"],
    tags: ["pillow", "memory-foam", "sleep", "cervical", "bedroom"],
    categorySlug: "bedding-pillows",
    sizes: [],
    colors: ["white"],
    images: { white: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80" },
  },

  // ── Books ────────────────────────────────────────────────────────────────
  {
    name: "Atomic Habits — James Clear",
    shortDescription: "The #1 bestselling guide to building good habits and breaking bad ones.",
    description: "Atomic Habits offers a proven framework for improving every day. James Clear, one of the world's leading experts on habit formation, reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviours that lead to remarkable results.",
    price: 1799,
    discountPercent: 0,
    brand: "Penguin Random House",
    sku: "BK-ATOM-HABITS",
    stock: 500,
    status: "published",
    highlights: ["#1 New York Times Bestseller", "Over 15 million copies sold", "Translated into 50+ languages", "Practical, science-backed strategies", "Paperback — 320 pages"],
    tags: ["book", "self-help", "habits", "productivity", "bestseller"],
    categorySlug: "books",
    sizes: [],
    colors: [],
    images: { default: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&q=80" },
  },

  // ── Sports ───────────────────────────────────────────────────────────────
  {
    name: "Adjustable Dumbbell Set (5–25kg)",
    shortDescription: "Space-saving adjustable dumbbells replacing 9 pairs in one.",
    description: "Replace an entire rack of weights with these innovative adjustable dumbbells. Turn the dial to select your weight from 2.5kg to 25kg in 2.5kg increments. The compact design stores easily and the durable moulded plates won't scratch floors.",
    price: 29900,
    discountPercent: 10,
    salePrice: 26910,
    brand: "IronFlex",
    sku: "IF-DUMB-ADJ",
    stock: 20,
    status: "published",
    highlights: ["Adjusts from 2.5kg to 25kg", "Replaces 9 pairs of dumbbells", "Quick-turn dial adjustment", "Anti-slip handle grip", "Tray included"],
    tags: ["dumbbells", "fitness", "gym", "weights", "home-gym"],
    categorySlug: "exercise-fitness",
    sizes: [],
    colors: [],
    images: { default: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80" },
  },
  {
    name: "Premium Yoga Mat",
    shortDescription: "6mm non-slip eco-friendly yoga mat with alignment lines.",
    description: "Made from natural tree rubber with a polyurethane top layer, this yoga mat provides exceptional grip even during hot yoga sessions. Alignment lines help beginners and experienced yogis maintain proper positioning. The 6mm thickness cushions joints without sacrificing stability.",
    price: 7900,
    discountPercent: 0,
    brand: "ZenFlow",
    sku: "ZF-YOGA-MAT",
    stock: 75,
    status: "published",
    highlights: ["Natural tree rubber base", "Non-slip polyurethane surface", "Alignment line printing", "6mm joint-cushioning thickness", "Includes carry strap"],
    tags: ["yoga", "mat", "fitness", "exercise", "eco-friendly"],
    categorySlug: "yoga-pilates",
    sizes: [],
    colors: ["purple", "black", "blue"],
    images: {
      purple: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800&q=80",
      black: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&q=80",
      blue: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80",
    },
  },

  // ── Toys ─────────────────────────────────────────────────────────────────
  {
    name: "LEGO City Police Station (743 pcs)",
    shortDescription: "Build and play with a detailed 3-level police station.",
    description: "This LEGO City Police Station set features a detailed 3-level building with a garage, prison cell, rooftop landing pad, and a fully equipped control room. Includes 6 minifigures: 2 police officers, 1 detective, 1 prisoner, and 2 crooks, plus vehicles and accessories.",
    price: 9900,
    discountPercent: 0,
    brand: "LEGO",
    sku: "LEGO-CITY-PS",
    stock: 55,
    status: "published",
    highlights: ["743 pieces", "6 minifigures included", "3-level building design", "Police helicopter pad", "Ages 6+"],
    tags: ["lego", "toys", "building", "kids", "police"],
    categorySlug: "toys-games",
    sizes: [],
    colors: [],
    images: { default: "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=800&q=80" },
  },

  // ── Pet Supplies ─────────────────────────────────────────────────────────
  {
    name: "Orthopedic Dog Bed (Large)",
    shortDescription: "Memory foam dog bed for large breeds with washable cover.",
    description: "Give your dog the rest they deserve with this orthopedic memory foam bed. The 8cm egg-crate foam base supports joints and reduces pressure points, making it ideal for senior dogs or those with arthritis. The soft plush cover is removable and machine washable.",
    price: 8900,
    discountPercent: 15,
    salePrice: 7565,
    brand: "PawComfort",
    sku: "PC-BED-LDOG",
    stock: 30,
    status: "published",
    highlights: ["8cm orthopedic egg-crate foam", "Machine-washable cover", "Non-slip bottom", "Suitable for large breeds (up to 45kg)", "Water-resistant liner"],
    tags: ["dog", "pet", "bed", "orthopedic", "large-dog"],
    categorySlug: "dog-supplies",
    sizes: [],
    colors: ["gray", "brown"],
    images: {
      gray: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&q=80",
      brown: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800&q=80",
    },
  },

  // ── Office ───────────────────────────────────────────────────────────────
  {
    name: "Ergonomic Mesh Office Chair",
    shortDescription: "Breathable mesh back chair with lumbar support and adjustable armrests.",
    description: "Designed for all-day comfort, this ergonomic office chair features a breathable mesh back panel that promotes airflow and prevents heat build-up. The adjustable lumbar support, seat height, tilt tension, and 3D armrests allow you to dial in the perfect seating position.",
    price: 34900,
    discountPercent: 20,
    salePrice: 27920,
    brand: "ErgoSeat",
    sku: "ES-CHAIR-MESH",
    stock: 18,
    status: "published",
    highlights: ["Breathable mesh back", "Adjustable lumbar support", "3D armrests", "Seat height 44–54cm", "Supports up to 135kg"],
    tags: ["chair", "office", "ergonomic", "mesh", "work-from-home"],
    categorySlug: "office-supplies",
    sizes: [],
    colors: ["black", "gray"],
    images: {
      black: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
      gray: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80",
    },
  },
];

async function main() {
  console.log(`Seeding ${products.length} products...`);
  let created = 0;

  for (const p of products) {
    const existing = await prisma.product.findFirst({ where: { name: p.name } });
    if (existing) { console.log(`  skip: ${p.name}`); continue; }

    await prisma.product.create({
      data: {
        name:            p.name,
        shortDescription: p.shortDescription,
        description:     p.description,
        price:           p.price,
        salePrice:       p.salePrice ?? null,
        discountPercent: p.discountPercent ?? 0,
        brand:           p.brand ?? null,
        sku:             p.sku ?? null,
        stock:           p.stock,
        status:          p.status,
        highlights:      p.highlights,
        tags:            p.tags,
        sizes:           p.sizes,
        colors:          p.colors,
        images:          p.images,
        category:        { connect: { slug: p.categorySlug } },
      },
    });
    console.log(`  ✓ ${p.name}`);
    created++;
  }

  console.log(`\nDone — created ${created} products.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
